spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true

server:
  port: 8023
